apiVersion: sagemaker.aws.amazon.com/v1
kind: HostingDeployment
metadata:
  name: k8s-sm-inference-host-endpoint
spec:
    region: us-east-1
    productionVariants:
        - variantName: AllTraffic
          modelName: tf-cifar10-resnet-model
          initialInstanceCount: 1
          instanceType: ml.c5.large
          initialVariantWeight: 1
    models:
        - name: tf-cifar10-resnet-model
          executionRoleArn: arn:aws:iam::446913493325:role/service-role/AmazonSageMaker-ExecutionRole-20180627T132602
          containers:
              - containerHostname: tensorflow
                modelDataUrl: s3://amitmukh-smmodel/jobs/k8s-sm-dist-training-script-dc39ea265fd911ea923f0eff5eeecd03/output/output.tar.gz
                image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:1.15.2-cpu-py36-ubuntu18.04
